# Generated by Django 4.2.4 on 2023-08-06 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.candidate')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='skill',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='MinExperience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Remote', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='perks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='postedDate',
            field=models.DateField(default=datetime.date(2023, 8, 6)),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='whoCanApply',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='JobSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='jobapplied',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplied',
            unique_together={('job', 'candidate')},
        ),
    ]
