# Generated by Django 4.2.4 on 2023-08-09 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplied_remove_jobskill_job_remove_jobskill_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isHiring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='isRemote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_before',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='postedDate',
            field=models.DateField(default=datetime.date(2023, 8, 9)),
        ),
    ]
