# Generated by Django 4.2.4 on 2023-08-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='internshipApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.candidate')),
            ],
        ),
        migrations.RemoveField(
            model_name='internshipskill',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='internshipskill',
            name='skill',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='internship',
            name='aboutCompany',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(default='Remote', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='numberofhiring',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='numberofopportunities',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='openings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='perks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='postedTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='skills',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='whoCanApply',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='apply_before',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='InternshipSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='internshipapplied',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.internship'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplied',
            unique_together={('internship', 'candidate')},
        ),
    ]
